### ISSUE TITLE
indexutils.findMismatches rounds up size of returned bitarray for large genome

### ISSUE THREAD

**Issue by glebkuznetsov** [Wyss/mauve-py#1]
I passed a genome of size 3971547 and the returned mismatch_lut had size 3971552. @benpruitt hypothesized that it rounded up to the next multiple of 8.

**Comment by grinner** [comment]
To clarify: calling len(mismatch_arr) returns 3971547 instead of 3971552?
The length should be the length of modified genome and not the reference genome.

```
    >> print(len(bitarray.bitarray(3971547)))
    3971547
```

**Comment by glebkuznetsov** [comment]
Yes, almost. `len(mismatch_arr)` returns 3971552, rather than the length of the genome 3971547.

**Comment by glebkuznetsov** [comment]
I don't have the code there anymore, but it was breaking when after calling this:
https://github.com/churchlab/genome-refactor/blob/d97b458d781d544aa416512d856af9641bd593a8/data/current_build/cleanup_annotations.py#L421

I would then pass idx_lut and my genomes to
https://github.com/Wyss/mascpcr/blob/782e6d79115bcb08cbb545654a1c0bcb388f2e22/mascpcr/indexing.py#L244

and the `mismatch_lut` returned by that was slightly longer.

**Comment by grinner** [comment]
can you call indexing.getGenomeLength() on the file whose length is wrong to check to see if that's erroring?

**Comment by glebkuznetsov** [comment]
Where is this `indexing.getGenomeLength()` function?

**Comment by grinner** [comment]
https://github.com/Wyss/mauve-py/blob/master/mauve/buildindex.py#L83

my bad

**Comment by glebkuznetsov** [comment]
getGenomeLength() returns the correct length.

**Comment by benpruitt** [comment]
Looks like this was an issue related to the way in which the bitarray.tofile and bitarray.fromfile methods work (in that they read/write an even number of bytes, so if your original bitarray is n bits where n%8 != 0, then the data that you write and subsequently read back in will be padded with zeros in the last byte). Closing this issue as the problem was a result of caching code in github.com/wyss/mascpcr rather than in this project.
